baseURL = 'http://localhost'
languageCode = 'pt-br'
title = 'Geode | Automação e Reviews de IA para a Sua Empresa'
theme = 'PaperMod'

[params]
  defaultTheme = "light"
  disableThemeToggle = true
  ShowReadingTime = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  [params.assets]
    favicon = "/img/favicon.svg"

  [params.label]
    icon = "/img/logo.svg"
    text = "Geode"
  
  [params.homeInfoParams]
    Title = "Geode: Inteligência em Software"
    Content = "Análises de ferramentas B2B focadas em ROI, risco e eficiência operacional. Sem hype, apenas negócios."

[menu]
  [[menu.main]]
    identifier = "vendas"
    name = "Vendas"
    url = "/vendas/"
    weight = 10
  [[menu.main]]
    identifier = "atendimento"
    name = "Atendimento"
    url = "/atendimento/"
    weight = 20
  [[menu.main]]
    identifier = "marketing"
    name = "Marketing"
    url = "/marketing/"
    weight = 30
  [[menu.main]]
    identifier = "produtividade"
    name = "Produtividade"
    url = "/produtividade/"
    weight = 40